export interface HangingStarConfig {
  position: string;
  height: string;
  textColorClass: string; // Full class name
  gradientClasses: string; // Full gradient classes
  size: string;
  icon: "★" | "✦";
  slow: boolean;
  delay: number;
}

export const HANGING_STARS: HangingStarConfig[] = [
  {
    position: "left-[5%]",
    height: "h-44",
    textColorClass: "text-yellow-400",
    gradientClasses: "via-yellow-400/50 to-yellow-400",
    size: "text-4xl",
    icon: "★",
    slow: false,
    delay: 0.1,
  },
  {
    position: "left-[12%]",
    height: "h-64",
    textColorClass: "text-amber-300",
    gradientClasses: "via-amber-300/50 to-amber-300",
    size: "text-5xl",
    icon: "★",
    slow: true,
    delay: 0.3,
  },
  {
    position: "left-[22%]",
    height: "h-36",
    textColorClass: "text-yellow-300",
    gradientClasses: "via-yellow-300/50 to-yellow-300",
    size: "text-3xl",
    icon: "✦",
    slow: false,
    delay: 0.2,
  },
  {
    position: "left-[32%]",
    height: "h-52",
    textColorClass: "text-amber-400",
    gradientClasses: "via-amber-400/50 to-amber-400",
    size: "text-5xl",
    icon: "★",
    slow: true,
    delay: 0.5,
  },
  {
    position: "left-[40%]",
    height: "h-28",
    textColorClass: "text-yellow-200",
    gradientClasses: "via-yellow-200/40 to-yellow-200",
    size: "text-2xl",
    icon: "✦",
    slow: false,
    delay: 0.4,
  },
  {
    position: "right-[38%]",
    height: "h-32",
    textColorClass: "text-amber-200",
    gradientClasses: "via-amber-200/40 to-amber-200",
    size: "text-2xl",
    icon: "✦",
    slow: true,
    delay: 0.45,
  },
  {
    position: "right-[28%]",
    height: "h-48",
    textColorClass: "text-yellow-400",
    gradientClasses: "via-yellow-400/50 to-yellow-400",
    size: "text-5xl",
    icon: "★",
    slow: false,
    delay: 0.35,
  },
  {
    position: "right-[18%]",
    height: "h-40",
    textColorClass: "text-amber-300",
    gradientClasses: "via-amber-300/50 to-amber-300",
    size: "text-3xl",
    icon: "✦",
    slow: true,
    delay: 0.25,
  },
  {
    position: "right-[10%]",
    height: "h-56",
    textColorClass: "text-yellow-300",
    gradientClasses: "via-yellow-300/50 to-yellow-300",
    size: "text-5xl",
    icon: "★",
    slow: false,
    delay: 0.15,
  },
  {
    position: "right-[3%]",
    height: "h-36",
    textColorClass: "text-amber-400",
    gradientClasses: "via-amber-400/50 to-amber-400",
    size: "text-4xl",
    icon: "★",
    slow: true,
    delay: 0.55,
  },
  // Extra decorative stars
  {
    position: "left-[8%]",
    height: "h-72",
    textColorClass: "text-yellow-200",
    gradientClasses: "via-yellow-200/30 to-yellow-200",
    size: "text-2xl",
    icon: "✦",
    slow: false,
    delay: 0.6,
  },
  {
    position: "left-[27%]",
    height: "h-60",
    textColorClass: "text-amber-200",
    gradientClasses: "via-amber-200/30 to-amber-200",
    size: "text-2xl",
    icon: "✦",
    slow: true,
    delay: 0.7,
  },
  {
    position: "right-[24%]",
    height: "h-68",
    textColorClass: "text-yellow-200",
    gradientClasses: "via-yellow-200/30 to-yellow-200",
    size: "text-2xl",
    icon: "✦",
    slow: false,
    delay: 0.65,
  },
  {
    position: "right-[6%]",
    height: "h-80",
    textColorClass: "text-amber-200",
    gradientClasses: "via-amber-200/30 to-amber-200",
    size: "text-xl",
    icon: "✦",
    slow: true,
    delay: 0.75,
  },
];
